// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzyojtqwyeeckpeavnah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6eW9qdHF3eWVlY2twZWF2bmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDgzMDcsImV4cCI6MjA2NjU4NDMwN30.dISBJ_7-CX0RVRVEfw3n3N7p6IQ4U-UDyEkIQno4iGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);